### PR TITLE
Execute __validate__ entry point before accepting a transaction

### PR DESCRIPTION
**Pull request by marioiordanov**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

Currently all transactions are not being validated prior actual execution.

Resolves: (https://github.com/keep-starknet-strange/madara/issues/69)

## What is the new behavior?

Transactions (Invoke, Declare, Deploy Account) are being validated using validate_tx method that invokes:
__validate__, __validate_declare__, __validate_deploy__ on the Cairo contract

## Does this introduce a breaking change?

No

### CODE REVIEW

**Comment by abdelhamidbakhta** [comment]
thanks a lot for this contribution, do you think you could add integration tests (in typescript) as well ?
And also would be awesome if you could run benchmarks and share the overhead on performance of adding this validation.

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Comment by abdelhamidbakhta** [comment]
@marioiordanov are you on the telegram group ?
u need to register to Only Dust to receive payments for your contributions.
https://app.onlydust.xyz/

**Comment by marioiordanov** [comment]
> @marioiordanov are you on the telegram group ?
> u need to register to Only Dust to receive payments for your contributions.
> https://app.onlydust.xyz/

Sorry for my delayed answer I am involved in another project. Actually I am in the telegram group.
About the typescript integration tests, I will make a PR when I find some free time.

**Comment by abdelhamidbakhta** [comment]
> > @marioiordanov are you on the telegram group ?
> > u need to register to Only Dust to receive payments for your contributions.
> > https://app.onlydust.xyz/
> 
> @abdelhamidbakhta Sorry for my delayed answer I am involved in another project. Actually I am in the telegram group. About the typescript integration tests, I will make a PR when I find some free time.
What is your handle on telegram ?

**Comment by marioiordanov** [comment]
@mrdninv

**Pull request merged**
