### PR TITLE
add feature flags for DA

### PR DESCRIPTION
**Pull request by apoorvsadana**

### CODE REVIEW

**Comment by EvolveArt** [comment]
@apoorvsadana Should we add steps in the CI to build/release these new images ?

**Comment by apoorvsadana** [comment]
You mean just having multiple images during the release or do we also need to build with these features for some CI? Right now the tests are passing so I guess there is nothing in the CI which needs avail/celestia as of now.

**Comment by EvolveArt** [comment]
> You mean just having multiple images during the release or do we also need to build with these features for some CI? Right now the tests are passing so I guess there is nothing in the CI which needs avail/celestia as of now.

Yes I meant having multiple released images, we will have integration tests for DA layer which will use these feature flags too but they are not fully ready yet.

**Review by EvolveArt — APPROVED** [review]

**Comment by apoorvsadana** [comment]
I will have to check the release workflow but do we need that right now? Maybe we can create an issue for that for someone to pick it up if that works?

**Review by tdelabro — APPROVED** [review]

**Pull request merged**
