### PR TITLE
feat: Implement AlephBFT Consensus in Madara

### LINKED ISSUE #909: feat: Implement AlephBFT Consensus in Madara
### Description

The goal of this issue is to implement the AlephBFT consensus algorithm in Madara. AlephBFT is a peer-reviewed consensus protocol that is used in the Aleph Zero blockchain. This will allow Madara to leverage the benefits of the AlephBFT consensus algorithm.

### Background

AlephBFT is a unique consensus algorithm used in the Aleph Zero blockchain. It is implemented in Rust and is based on the Substrate framework. The Aleph node is based on a Substrate node where the default finality gadget (GRANDPA) has been replaced with AlephBFT. Block authoring is realized with Substrate's Aura.

### Tasks

1. **Research**: Understand the AlephBFT consensus algorithm and how it can be integrated with Madara.
2. **Design**: Create a design document detailing how the AlephBFT consensus will be implemented in Madara. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new consensus algorithm is fully functional.
4. **Testing**: Write comprehensive tests to ensure the new consensus algorithm works as expected and does not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new consensus algorithm.

### Acceptance Criteria

- The AlephBFT consensus algorithm is fully implemented in Madara.
- The implementation passes all tests.
- The project documentation is updated to reflect the new consensus algorithm.

### Resources

- [AlephBFT Documentation](https://docs.alephzero.org/aleph-zero/explore/alephbft-consensus)
- [AlephZero Substrate Node](https://github.com/Cardinal-Cryptography/aleph-node/tree/main)

### PR DESCRIPTION
**Pull request by hhamud**
# Pull Request type
* Closes #909 

Please add the labels corresponding to the type of changes your PR introduces:

- Feature
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?
Current behaviour is that madara only uses Aura and Grandpa for its consensus mechanism.

Resolves: #NA

## What is the new behavior?
Implements additional consensus crate 

Adds AlephBFT consensus to madara

## Does this introduce a breaking change?
No

### CODE REVIEW

**Comment by apoorvsadana** [comment]
@hhamud, we won't want this feature on the main repo ideally. Let's keep it in its own fork for now with good instructions on how to add it to Madara if someone wants to.

**Comment by hhamud** [comment]
> @hhamud, we won't want this feature on the main repo ideally. Let's keep it in its own fork for now with good instructions on how to add it to Madara if someone wants to.

What would be the general plan for this PR? @tdelabro @apoorvsadana 

My idea for this PR would be to allow users to switch consensus libraries on the fly, so they would either use this or GRANDPA for block finalisation. I would gate it this behind a feature flag, e.g "consensus/aleph" and I would not want to separate this out into its own repository as that makes bug fixing or making additional changes more difficult.

**Comment by apoorvsadana** [comment]
Eventually we would like to support many consensus algorithms with Madara. So we've created a new [Madara extensions repo](https://github.com/keep-starknet-strange/madara-extentions) for all such cool plugins that can be used out of the box with Madara. The exact structure of the repo is yet to be decided, maybe we have all the pallets and steps on how to integrate them. How do you think we should do it @EvolveArt?

**Comment by hhamud** [comment]
> Eventually we would like to support many consensus algorithms with Madara. So we've created a new [Madara extensions repo](https://github.com/keep-starknet-strange/madara-extentions) for all such cool plugins that can be used out of the box with Madara. The exact structure of the repo is yet to be decided, maybe we have all the pallets and steps on how to integrate them. How do you think we should do it @EvolveArt?

Ok that makes sense. I'll continue working on this and then once the other repo is ready, I'll just move everything over and refactor anything thats needed to change.

**Pull request closed without merging**
