### PR TITLE
chore(rpc): update `estimateFee` according to specs

### PR DESCRIPTION
**Pull request by exp-table**
# Pull Request type

Updating `estimateFee`JSON RPC API method so it follows the latest specs.

## What is the current behavior?

Currently `estimateFee` only takes a single transaction, while it should take an array according to the new specs.

Resolves: #795

## What is the new behavior?

`estimateFee` now takes an array of transactions, according to the new specs.

## Does this introduce a breaking change?

Yes.

## Other information

While the TS tests have been updated, the `starknet`dependency does seem to support the latest spec regarding `estimateFee`, breaking the test given `provider.getEstimateFee` expects a single tx and not an array.

### CODE REVIEW

**Comment by apoorvsadana** [comment]
Can you search for `FIXME: https://github.com/keep-starknet-strange/madara/issues/795` in the code and fix the two test cases according to the new spec as well?

**Comment by exp-table** [comment]
> Can you search for `FIXME: https://github.com/keep-starknet-strange/madara/issues/795` in the code and fix the two test cases according to the new spec as well?

I would but as specified above, we rely on an external dependency `starknet` which doesn't follow the latest spec for `estimateFee` [here](https://www.starknetjs.com/docs/API/classes/RpcProvider#getestimatefee). 

I can put this as a draft while they eventually modify it!

**Comment by apoorvsadana** [comment]
sorry, might have missed your original PR details but I think you've fixed the test now is that correct? i remember `starknet` sending an array of requests because of which it was failing for me intitially

**Comment by exp-table** [comment]
> sorry, might have missed your original PR details but I think you've fixed the test now is that correct? i remember `starknet` sending an array of requests because of which it was failing for me intitially

Yeah, I mistook `SequencerProvider` with `RpcProvider` ...

**Review by EvolveArt — CHANGES_REQUESTED** [review]
Just need to add a few more tests to test `getEstimateFeeBulk` edge cases otherwise LGTM

**Review by EvolveArt — APPROVED** [review]
lgtm

**Pull request merged**
