### PR TITLE
Add Abi to contract class

### PR DESCRIPTION
**Pull request by Cheelax**
Adding abi reading when declaring a new contract class

# Pull Request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: (https://github.com/keep-starknet-strange/madara/issues/105)

# What is the new behavior?
Added the bounded vec containing abi inside the ContractClassWrapper and fixed 

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Review by EvolveArt — APPROVED** [review]
lgtm

Please create an issue if you have ideas of what we could do with the `abi` field within the sequencer runtime

**Review by EvolveArt — CHANGES_REQUESTED** [review]
looks like 1 test is still failing in the CI

**Comment by abdelhamidbakhta** [comment]
hey @Cheelax are you still working on it ? could you please resolve conflicts and fix failing tests ?

**Comment by Cheelax** [comment]
Hey @abdelhamidbakhta 
Not really working on this one right now.
I can solve conflicts if you want, but regarding the tests I had some inconsistency in the results on my end (sometimes passing, sometimes not). I talked about it with @EvolveArt, don't know if he has some info about this problem?

**Comment by EvolveArt** [comment]
> Hey @abdelhamidbakhta 
> 
> Not really working on this one right now.
> 
> I can solve conflicts if you want, but regarding the tests I had some inconsistency in the results on my end (sometimes passing, sometimes not). I talked about it with @EvolveArt, don't know if he has some info about this problem?

Unfortunately I wasn't able to reproduce the issue..
Would be great if you could resolve conflicts, would appreciate it then I think it's ready to be merged.

**Comment by Cheelax** [comment]
Will do it tonight.
Sorry I can't help you more with the test

**Comment by Cheelax** [comment]
Conflicts are solved. It still looks like there is a problem on a test. I would like some advices on this one

**Comment by EvolveArt** [comment]
> Conflicts are solved. It still looks like there is a problem on a test. I would like some advices on this one

I will take a look.

**Comment by abdelhamidbakhta** [comment]
> 

@EvolveArt any way we can move on this one ?

**Comment by EvolveArt** [comment]
> > 
> 
> @EvolveArt any way we can move on this one ?

**Pull request closed without merging**
