### PR TITLE
Remove checkboxes from issue and PR template

### PR DESCRIPTION
**Pull request by ClementWalter**
# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [x] Other (please describe): github template

# What is the current behavior?

The feature request template and the pull request template use checkboxes (`[ ]`) to help the dev choose in between several categories of issues/update, etc.

However, the `[ ]` is interpreted by GitHub as a task list and GitHub consequently considers that issues and PR have partial tasks execution.

# What is the new behavior?

Updated the comments to make the dev choose differently.

# Does this introduce a breaking change?

No

# Other information

I have also renamed "Issue number" into "Resolves" as this is a special keywords used by github to link issues and PR

### CODE REVIEW

**Comment by ClementWalter** [comment]
see task list in issues 
image

**Comment by LucasLvy** [comment]
WDYT of removing the list and using labels ?

**Comment by ClementWalter** [comment]
> WDYT of removing the list and using labels ?

why not yes, I'm actually trying to understand how to get the best out of github project management and work organization features. Labels seem for sure a better place to tag PR

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Pull request merged**
