### PR TITLE
fix: changed log::info to println

### PR DESCRIPTION
**Pull request by apoorvsadana**
The file copy was being logged using `log::info`. However, the logger is not initialised until the node starts (inside `create_runner`). Hence, I have changed the code to use println! instead

### CODE REVIEW

**Comment by d-roak** [comment]
I don't think this is a good solution

**Comment by apoorvsadana** [comment]
Ya I am not as well about what other implementations are possible, open to new approaches. What do you think are the issues though @d-roak?

**Comment by d-roak** [comment]
@apoorvsadana i think the log::info is the way to go. The thing is, we should discover why it's not logging in that scope. It might be related with it being in the pallet crate (?)

**Comment by apoorvsadana** [comment]
It doesn't log in that scope because the logger isn't initialized until `create_runner`. We can  maybe figure out a way to initialise it before (I googled a little but didn't find much, will need to probably go deeper). However, event frontier seems to use the same approach for logging before the node starts

https://github.com/paritytech/frontier/blob/aab7cfc3e038ec65ca4d1b2bc3d68e51aa162514/template/node/src/command.rs#L144

**Comment by tdelabro** [comment]
We can maybe have another logger? For launch?

**Comment by apoorvsadana** [comment]
Right, but I am just trying to understand what's the main issue with `println` that we want to tackle - `std` dependency, logging levels etc. Then we can ideally decide what's the correct solution for us.

**Comment by tdelabro** [comment]
My problem with println is that it will print everytime, when most of the time the user won't care about what will be displayed. So we should be able to hide it easily. Log levels are a good solution for this.

**Comment by apoorvsadana** [comment]
Got it, this makes sense. Will find what logger can we use.

**Comment by tdelabro** [comment]
Maybe we should just move the logger initialization from the node to the CLI part of the code? Wdyt?

**Pull request closed without merging**
