### PR TITLE
Simnode integration updates

### LINKED ISSUE #427: Simnode for integration tests
Simnode is an integration testing environment for substrate runtimes that allows you to create extrinsics from any account and full control over block production.

Consider integrating to Madara for integration tests

https://simnode.polytope.technology

### PR DESCRIPTION
**Pull request by shamb0**
**Fixes #427**

Integrates sc-simnode, a Substrate-based simulation node
sc-simnode allows developers to fork their live chain state and run all kinds of simulation tests on the runtime. This can be used to test new features, debug code, and stress test the network.

# Pull Request type

- Testing

## Does this introduce a breaking change?

**Request to the Team:**

Most changes made to the node and runtime layers are useful for internal debugging and the QA process. It is safe to keep these changes away from production code and maintain them in a separate branch.

### CODE REVIEW

**Comment by shamb0** [comment]
Hi,

@abdelhamidbakhta, @LucasLvy 

## Quick Update on draft PR status

I have completed the basic bring up of simnode integration to madara stack. I have also done a sanity check with the RPC commands `engine_createBlock` and `simnode_revertBlocks`, both of which are working fine.

image

**Low-lights**

* The dependency `sc-simnode` needs to be upgraded to polkadot-v0.9.43. I have mapped it to my fork branch, and I need to do some cleanup and make a PR to `sc-simnode` for upstream codebase merger.
    
    - https://github.com/shamb0/sc-simnode/tree/shamb0/move-polkadot-v0.9.43

* In the current bring-up, I ignored the `starknet` RPC from `rpc_extensions_builder`, due to some type conflict and dependency issues. I am analyzing the code to find a proper fix. If you have any suggestions, please let me know.

## Test Report

### Use-case-01: Testing `engine_createBlock()` RPC Command

**Command 01**

```shell
curl http://127.0.0.1:9944 -d '{"id":29,"jsonrpc":"2.0","method":"engine_createBlock","params":[true, true]}' -H "Content-Type: application/json"
```

**Response 01**

```shell
{"jsonrpc":"2.0","result":{"hash":"0x709e5bf97e1f16dd7e9310fd5e9fc0cb4ee210780b9c2f5a53563ce1d9ac2698","aux":{"header_only":false,"clear_justification_requests":false,"needs_justification":false,"bad_justification":false,"is_new_best":true}},"id":29}%
```

**Command 02**

```shell
curl http://127.0.0.1:9944 -d '{"id":29,"jsonrpc":"2.0","method":"engine_createBlock","params":[false, true]}' -H "Content-Type: application/json"
```

**Response 02**

```shell
{"jsonrpc":"2.0","error":{"code":12000,"message":"Transaction pool is empty, set create_empty to true, if you want to create empty blocks"},"id":29}%
```

### Use-case-02: Testing `simnode_revertBlocks()` RPC Command

**Command 01**

```shell
curl http://127.0.0.1:9944 -d '{"id":29,"jsonrpc":"2.0","method":"simnode_revertBlocks","params":[2]}' -H "Content-Type: application/json"
```

**Response 01**

```shell
{"jsonrpc":"2.0","result":null,"id":29}%
```

**Comment by shamb0** [comment]
Hi,

@abdelhamidbakhta, @LucasLvy

I have integrated Starknet RPC to simnode context, but I would appreciate your review and guidance. In the current integration, the syncing RPC Endpoint will not work because it depends on the SyncingEngine of the network services.

**Based on my code analysis, I have found the following:**

Under the simnode simulation context, all network services are shut down and the SyncingEngine is not active. Therefore, the syncing() RPC API cannot obtain the best seen (highest) block number.

I would like to discuss these findings with you and get your feedback on how to proceed.

**Comment by abdelhamidbakhta** [comment]
> Hi,
> 
> @abdelhamidbakhta, @LucasLvy
> 
> I have integrated Starknet RPC to simnode context, but I would appreciate your review and guidance. In the current integration, the syncing RPC Endpoint will not work because it depends on the SyncingEngine of the network services.
> 
> **Based on my code analysis, I have found the following:**
> 
> Under the simnode simulation context, all network services are shut down and the SyncingEngine is not active. Therefore, the syncing() RPC API cannot obtain the best seen (highest) block number.
> 
> I would like to discuss these findings with you and get your feedback on how to proceed.

@LucasLvy please take a look. @shamb0 thank you very much for this work

**Comment by EvolveArt** [comment]
Hey @shamb0 if you can send a message on the Madara Telegram group that'd be great so we can hop on a call and discuss this PR as there is a lot of material and I want to make sure I understand every part of it. 

Thanks!

**Comment by shamb0** [comment]
> 

Hey @EvolveArt,

Thank you for your interest. We will discuss the recent changes to the integration of the simnode simulation framework into Madara.

From the latest changes, here are the main points to consider:

- The simnode launch function has been successfully integrated into Madara, providing a full node environment.
- This integration allows us to effectively leverage the SyncingEngine and syncing() RPC API.

My Telegram handle is "@shamb0". Would you be available for a discussion call via Telegram at around 5:30 PM CET? Please let me know if this time works for you.

Thank you, and I look forward to our discussion.

**Pull request closed without merging**
