### PR TITLE
dev: return JSON-RPC error for unimplemented Starknet RPC endpoint

### PR DESCRIPTION
**Pull request by kariy**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #573 

## What is the new behavior?

- Add a new variant for `StarknetRpcApiError`, `UnimplementedMethod`.
- Return `UnimplementedMethod` for Starknet RPC endpoint that is not yet implemented.

### CODE REVIEW

**Comment by kariy** [comment]
just realized there's only one unimplemented method here.. is there any more that i might have missed?

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
please add an integration test to cover this new error

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Comment by abdelhamidbakhta** [comment]
> just realized there's only one unimplemented method here.. is there any more that i might have missed?

nope all good

**Pull request merged**
