### PR TITLE
feat: replace unwrap by error handling 🔨 #165

### LINKED ISSUE #165: feat(quality): replace `unwrap` by error handling 🔨
# Feature Request

**Describe the Feature Request**

`unwrap`s are dangerous to have within the runtime as a `panic` would simply crash the blockchain. 
Moreover it would impact forkless upgrades in the future.

**Describe Preferred Solution**

Go through the codebase and look for `.unwrap()`, replace them with custom errors that then propage to the pallet as `RuntimeError`s.

**Acceptance Crtieria**

No need to replace **ALL** unwraps within a single PR, even small PRs would be very helpful.

### PR DESCRIPTION
**Pull request by 0xEniotna**
# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

There are some `unwrap()` functions that are used in the code.
unwraps are dangerous to have within the runtime as a panic would simply crash the blockchain.
Moreover it would impact forkless upgrades in the future.

Issue Number: fixes #165

# What is the new behavior?

unwraps are replaced by error handling patterns with pallet custom errors.

# Other information

This PR only focuses on a single type of errors, `Pending::<T>::try_append(transaction.clone())`

### CODE REVIEW

**Comment by 0xEniotna** [comment]
I'm new to rust, would this be a good solution ? I went for the most simple fixes there on a single type of errors

**Comment by abdelhamidbakhta** [comment]
> I'm new to rust, would this be a good solution ? I went for the most simple fixes there on a single type of errors. If this solution is OK, i'll add more commits to the PR

Yeah `map_err` is the way to go

**Comment by EvolveArt** [comment]
Please make sure to run `cargo fmt` and `cargo clippy -D warnings` @0xEniotna

**Comment by 0xEniotna** [comment]
Sorry I don't have much time this week to work. I'm pushing what I have already. Will come back to it later.

**Review by EvolveArt — APPROVED** [review]
lgtm

**Pull request merged**
