### PR TITLE
feat: initialise proving / data availability

### PR DESCRIPTION
**Pull request by drspacemn**
Initialize KV Store for: fact storage, last proven block, cairo job keys, and cairo job statuses

Spawn task for mock proving
- Store mock fact in madara db
- Submit mock pie to the GPS/Prover
- Store the cairo job key in the madara db 

Spawn task for mock update
- Query last proven block from core contracts
- Check the associated job status
- If the proved, mock the updateState write to the Core Contracts

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- [x] Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

No concept of proving the state transition

Resolves: #693 

## Does this introduce a breaking change?

Yes 

Users need to remove their local database as a new column is initialized.

It appears the `purge chain` cli command is broken. Action item to open a ticket for bug fix

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Yo shouldn't compute the DA at prove_current_block(). It should be computed by running the StarkNet OS cairo program.
The state diff should be computed in terms of what the OS program expects. If the OS is run inside a cairo-vm runner, with a custom hint, then this can be any code that can retrieve thins like txs, contract definitions, block hash and timestamp, nonces, etc...

The OS program then outputs the DA using the "output builtin".

**Comment by drspacemn** [comment]
> Yo shouldn't compute the DA at prove_current_block(). It should be computed by running the StarkNet OS cairo program. The state diff should be computed in terms of what the OS program expects. If the OS is run inside a cairo-vm runner, with a custom hint, then this can be any code that can retrieve thins like txs, contract definitions, block hash and timestamp, nonces, etc...
> 
> The OS program then outputs the DA using the "output builtin".

Okay yes understood. I added this comment in the place I expect to run the [OS](https://github.com/keep-starknet-strange/madara/blob/4faa30ab97d4413cb98fa7e4b583e3a151676261/crates/client/data-availability/src/lib.rs#L86).

I've submitted the issue for `cairo-vm` to output the PIE after the run of the [OS](https://github.com/lambdaclass/cairo-vm/issues/1305). In your opinion, is this something we can format manually from the vm run itself as a short term solution?

**Comment by spapinistarkware** [comment]
> > Yo shouldn't compute the DA at prove_current_block(). It should be computed by running the StarkNet OS cairo program. The state diff should be computed in terms of what the OS program expects. If the OS is run inside a cairo-vm runner, with a custom hint, then this can be any code that can retrieve thins like txs, contract definitions, block hash and timestamp, nonces, etc...
> > The OS program then outputs the DA using the "output builtin".
> 
> Okay yes understood. I added this comment in the place I expect to run the [OS](https://github.com/keep-starknet-strange/madara/blob/a1082af16da1a40244e17eac1339e363fa841282/crates/client/data-availability/src/lib.rs#L48).
> 
Looks good
> Is there any point in supporting the pre v0.11.0 DA format(+ pre v0.11.0 SN OS I'm assuming) or just use the DA output from the current version of the OS?
> 
latter
> I've submitted the issue for `cairo-vm` to output the PIE after the run of the [OS](https://github.com/lambdaclass/cairo-vm/issues/1305). In your opinion, is this something we can format manually from the vm run itself as a short term solution?

It'll probably be the same amount of work as just making the feature in cairo-vm, which is not very hard I think.

**Comment by tdelabro** [comment]
@drspacemn What should we do with this PR?

**Pull request closed without merging**
